/**
 * Source of truth for the Dutch verb dataset.
 *
 * This file holds only the parts of a conjugation that require linguistic
 * judgement. Everything mechanical - person endings, the 't kofschip rule,
 * participle assembly, auxiliary agreement - is derived by build-verbs.mjs.
 *
 * Run `npm run build:verbs` after editing to regenerate src/data/verbs.json.
 */

/**
 * Weak (regular) verbs: [infinitive, stem, aux, english]
 *
 * `stem` is the spelled present-tense ik-form (open-syllable lengthening and
 * final devoicing already applied: leven -> leef, reizen -> reis).
 * The -de/-te choice is derived from the *infinitive*, not the stem, so
 * underlyingly voiced finals stay correct: reizen -> reisde, leven -> leefde.
 *
 * `aux` is 'hebben', 'zijn', or both joined by a pipe when both are current,
 * commoner one first. Both readings are then accepted as correct answers.
 */
export const WEAK = [
  ['aarzelen', 'aarzel', 'hebben', 'to hesitate'],
  ['antwoorden', 'antwoord', 'hebben', 'to answer'],
  ['bedanken', 'bedank', 'hebben', 'to thank'],
  ['bedoelen', 'bedoel', 'hebben', 'to mean'],
  ['behoren', 'behoor', 'hebben', 'to belong'],
  ['bekleden', 'bekleed', 'hebben', 'to hold (an office)'],
  ['beleven', 'beleef', 'hebben', 'to experience'],
  ['bellen', 'bel', 'hebben', 'to call, to phone'],
  ['beloven', 'beloof', 'hebben', 'to promise'],
  ['bereiken', 'bereik', 'hebben', 'to reach'],
  ['beslissen', 'beslis', 'hebben', 'to decide'],
  ['bestellen', 'bestel', 'hebben', 'to order'],
  ['betalen', 'betaal', 'hebben', 'to pay'],
  ['betekenen', 'beteken', 'hebben', 'to mean'],
  ['bewaren', 'bewaar', 'hebben', 'to keep, to store'],
  ['bloeien', 'bloei', 'hebben', 'to bloom'],
  ['blozen', 'bloos', 'hebben', 'to blush'],
  ['boeken', 'boek', 'hebben', 'to book'],
  ['boren', 'boor', 'hebben', 'to drill'],
  ['bouwen', 'bouw', 'hebben', 'to build'],
  ['branden', 'brand', 'hebben', 'to burn'],
  ['brullen', 'brul', 'hebben', 'to roar'],
  ['controleren', 'controleer', 'hebben', 'to check'],
  ['dansen', 'dans', 'hebben', 'to dance'],
  ['danken', 'dank', 'hebben', 'to thank'],
  ['dekken', 'dek', 'hebben', 'to cover'],
  ['delen', 'deel', 'hebben', 'to share, to divide'],
  ['dienen', 'dien', 'hebben', 'to serve'],
  ['doden', 'dood', 'hebben', 'to kill'],
  ['dopen', 'doop', 'hebben', 'to baptise, to dip'],
  ['douchen', 'douch', 'hebben', 'to shower'],
  ['draaien', 'draai', 'hebben', 'to turn'],
  ['dreigen', 'dreig', 'hebben', 'to threaten'],
  ['drogen', 'droog', 'hebben', 'to dry'],
  ['dromen', 'droom', 'hebben', 'to dream'],
  ['drukken', 'druk', 'hebben', 'to press, to print'],
  ['dulden', 'duld', 'hebben', 'to tolerate'],
  ['duren', 'duur', 'hebben', 'to last'],
  ['duwen', 'duw', 'hebben', 'to push'],
  ['eindigen', 'eindig', 'hebben|zijn', 'to end'],
  ['eisen', 'eis', 'hebben', 'to demand'],
  ['feliciteren', 'feliciteer', 'hebben', 'to congratulate'],
  ['fietsen', 'fiets', 'hebben|zijn', 'to cycle'],
  ['filmen', 'film', 'hebben', 'to film'],
  ['fluisteren', 'fluister', 'hebben', 'to whisper'],
  ['fotograferen', 'fotografeer', 'hebben', 'to photograph'],
  ['functioneren', 'functioneer', 'hebben', 'to function'],
  ['gapen', 'gaap', 'hebben', 'to yawn'],
  ['gebeuren', 'gebeur', 'zijn', 'to happen'],
  ['gebruiken', 'gebruik', 'hebben', 'to use'],
  ['geloven', 'geloof', 'hebben', 'to believe'],
  ['gillen', 'gil', 'hebben', 'to scream'],
  ['glimlachen', 'glimlach', 'hebben', 'to smile'],
  ['gooien', 'gooi', 'hebben', 'to throw'],
  ['grinniken', 'grinnik', 'hebben', 'to chuckle'],
  ['groeien', 'groei', 'zijn', 'to grow'],
  ['groeten', 'groet', 'hebben', 'to greet'],
  ['haasten', 'haast', 'hebben', 'to hurry'],
  ['haken', 'haak', 'hebben', 'to hook, to crochet'],
  ['halen', 'haal', 'hebben', 'to fetch, to get'],
  ['handelen', 'handel', 'hebben', 'to act, to trade'],
  ['hechten', 'hecht', 'hebben', 'to attach'],
  ['heersen', 'heers', 'hebben', 'to rule'],
  ['herhalen', 'herhaal', 'hebben', 'to repeat'],
  ['herinneren', 'herinner', 'hebben', 'to remind, to remember'],
  ['herkennen', 'herken', 'hebben', 'to recognise'],
  ['herstellen', 'herstel', 'hebben|zijn', 'to repair, to recover'],
  ['hijgen', 'hijg', 'hebben', 'to pant'],
  ['hoesten', 'hoest', 'hebben', 'to cough'],
  ['hopen', 'hoop', 'hebben', 'to hope'],
  ['horen', 'hoor', 'hebben', 'to hear'],
  ['huilen', 'huil', 'hebben', 'to cry'],
  ['huren', 'huur', 'hebben', 'to rent'],
  ['informeren', 'informeer', 'hebben', 'to inform'],
  ['installeren', 'installeer', 'hebben', 'to install'],
  ['interesseren', 'interesseer', 'hebben', 'to interest'],
  ['joggen', 'jog', 'hebben', 'to jog'],
  ['juichen', 'juich', 'hebben', 'to cheer'],
  ['kalmeren', 'kalmeer', 'hebben', 'to calm'],
  ['kammen', 'kam', 'hebben', 'to comb'],
  ['kauwen', 'kauw', 'hebben', 'to chew'],
  ['kennen', 'ken', 'hebben', 'to know (be acquainted with)'],
  ['klagen', 'klaag', 'hebben', 'to complain'],
  ['kleden', 'kleed', 'hebben', 'to dress'],
  ['knikken', 'knik', 'hebben', 'to nod'],
  ['knippen', 'knip', 'hebben', 'to cut (with scissors)'],
  ['knopen', 'knoop', 'hebben', 'to knot'],
  ['kloppen', 'klop', 'hebben', 'to knock'],
  ['koken', 'kook', 'hebben', 'to cook'],
  ['kosten', 'kost', 'hebben', 'to cost'],
  ['krabben', 'krab', 'hebben', 'to scratch'],
  ['kraken', 'kraak', 'hebben', 'to crack'],
  ['kussen', 'kus', 'hebben', 'to kiss'],
  ['kwetsen', 'kwets', 'hebben', 'to hurt, to offend'],
  ['landen', 'land', 'zijn', 'to land'],
  ['leggen', 'leg', 'hebben', 'to lay, to put'],
  ['leiden', 'leid', 'hebben', 'to lead'],
  ['lenen', 'leen', 'hebben', 'to lend, to borrow'],
  ['leren', 'leer', 'hebben', 'to learn, to teach'],
  ['letten', 'let', 'hebben', 'to pay attention'],
  ['leven', 'leef', 'hebben', 'to live, to be alive'],
  ['lossen', 'los', 'hebben', 'to unload'],
  ['luiden', 'luid', 'hebben', 'to ring, to read (of a text)'],
  ['luisteren', 'luister', 'hebben', 'to listen'],
  ['lukken', 'luk', 'zijn', 'to succeed'],
  ['maaien', 'maai', 'hebben', 'to mow'],
  ['mailen', 'mail', 'hebben', 'to email'],
  ['maken', 'maak', 'hebben', 'to make'],
  ['marcheren', 'marcheer', 'hebben|zijn', 'to march'],
  ['melden', 'meld', 'hebben', 'to report'],
  ['mengen', 'meng', 'hebben', 'to mix'],
  ['merken', 'merk', 'hebben', 'to notice'],
  ['mikken', 'mik', 'hebben', 'to aim'],
  ['missen', 'mis', 'hebben', 'to miss'],
  ['mompelen', 'mompel', 'hebben', 'to mumble'],
  ['monteren', 'monteer', 'hebben', 'to assemble'],
  ['mopperen', 'mopper', 'hebben', 'to grumble'],
  ['naderen', 'nader', 'hebben|zijn', 'to approach'],
  ['negeren', 'negeer', 'hebben', 'to ignore'],
  ['nodigen', 'nodig', 'hebben', 'to invite'],
  ['noemen', 'noem', 'hebben', 'to name, to call'],
  ['observeren', 'observeer', 'hebben', 'to observe'],
  ['oefenen', 'oefen', 'hebben', 'to practise'],
  ['ontdekken', 'ontdek', 'hebben', 'to discover'],
  ['ontmoeten', 'ontmoet', 'hebben', 'to meet'],
  ['ontwikkelen', 'ontwikkel', 'hebben', 'to develop'],
  ['openen', 'open', 'hebben', 'to open'],
  ['opereren', 'opereer', 'hebben', 'to operate'],
  ['ordenen', 'orden', 'hebben', 'to arrange'],
  ['organiseren', 'organiseer', 'hebben', 'to organise'],
  ['overtuigen', 'overtuig', 'hebben', 'to convince'],
  ['pakken', 'pak', 'hebben', 'to grab, to pack'],
  ['parkeren', 'parkeer', 'hebben', 'to park'],
  ['passen', 'pas', 'hebben', 'to fit'],
  ['pauzeren', 'pauzeer', 'hebben', 'to pause'],
  ['plaatsen', 'plaats', 'hebben', 'to place'],
  ['plannen', 'plan', 'hebben', 'to plan'],
  ['planten', 'plant', 'hebben', 'to plant'],
  ['plukken', 'pluk', 'hebben', 'to pick'],
  ['poetsen', 'poets', 'hebben', 'to polish, to brush'],
  ['praten', 'praat', 'hebben', 'to talk'],
  ['presenteren', 'presenteer', 'hebben', 'to present'],
  ['prikken', 'prik', 'hebben', 'to prick'],
  ['proberen', 'probeer', 'hebben', 'to try'],
  ['produceren', 'produceer', 'hebben', 'to produce'],
  ['proeven', 'proef', 'hebben', 'to taste'],
  ['raken', 'raak', 'hebben', 'to touch, to hit'],
  ['reageren', 'reageer', 'hebben', 'to react'],
  ['redden', 'red', 'hebben', 'to save, to rescue'],
  ['redeneren', 'redeneer', 'hebben', 'to reason'],
  ['regelen', 'regel', 'hebben', 'to arrange'],
  ['regenen', 'regen', 'hebben', 'to rain'],
  ['rekenen', 'reken', 'hebben', 'to calculate'],
  ['remmen', 'rem', 'hebben', 'to brake'],
  ['rennen', 'ren', 'hebben|zijn', 'to run'],
  ['repareren', 'repareer', 'hebben', 'to repair'],
  ['reserveren', 'reserveer', 'hebben', 'to reserve'],
  ['reizen', 'reis', 'hebben|zijn', 'to travel'],
  ['richten', 'richt', 'hebben', 'to aim, to direct'],
  ['rillen', 'ril', 'hebben', 'to shiver'],
  ['roeien', 'roei', 'hebben|zijn', 'to row'],
  ['roeren', 'roer', 'hebben', 'to stir'],
  ['roken', 'rook', 'hebben', 'to smoke'],
  ['ruilen', 'ruil', 'hebben', 'to exchange'],
  ['ruimen', 'ruim', 'hebben', 'to clear'],
  ['rusten', 'rust', 'hebben', 'to rest'],
  ['schaatsen', 'schaats', 'hebben|zijn', 'to skate'],
  ['schakelen', 'schakel', 'hebben', 'to switch'],
  ['schamen', 'schaam', 'hebben', 'to be ashamed'],
  ['schelen', 'scheel', 'hebben', 'to matter'],
  ['schikken', 'schik', 'hebben', 'to arrange, to suit'],
  ['schilderen', 'schilder', 'hebben', 'to paint'],
  ['schokken', 'schok', 'hebben', 'to shock'],
  ['schoppen', 'schop', 'hebben', 'to kick'],
  ['schreeuwen', 'schreeuw', 'hebben', 'to scream'],
  ['serveren', 'serveer', 'hebben', 'to serve'],
  ['slenteren', 'slenter', 'hebben|zijn', 'to saunter'],
  ['slepen', 'sleep', 'hebben', 'to drag'],
  ['slikken', 'slik', 'hebben', 'to swallow'],
  ['smaken', 'smaak', 'hebben', 'to taste'],
  ['smeren', 'smeer', 'hebben', 'to grease, to spread'],
  ['snappen', 'snap', 'hebben', 'to get, to understand'],
  ['snurken', 'snurk', 'hebben', 'to snore'],
  ['solliciteren', 'solliciteer', 'hebben', 'to apply for a job'],
  ['sparen', 'spaar', 'hebben', 'to save (money)'],
  ['spelen', 'speel', 'hebben', 'to play'],
  ['spoelen', 'spoel', 'hebben', 'to rinse'],
  ['sporten', 'sport', 'hebben', 'to do sports'],
  ['spotten', 'spot', 'hebben', 'to mock, to spot'],
  ['spreiden', 'spreid', 'hebben', 'to spread'],
  ['staren', 'staar', 'hebben', 'to stare'],
  ['steunen', 'steun', 'hebben', 'to support'],
  ['stichten', 'sticht', 'hebben', 'to found'],
  ['stoppen', 'stop', 'hebben', 'to stop'],
  ['storen', 'stoor', 'hebben', 'to disturb'],
  ['storten', 'stort', 'hebben', 'to deposit, to dump'],
  ['straffen', 'straf', 'hebben', 'to punish'],
  ['stralen', 'straal', 'hebben', 'to shine, to beam'],
  ['strelen', 'streel', 'hebben', 'to caress'],
  ['stromen', 'stroom', 'hebben|zijn', 'to flow'],
  ['studeren', 'studeer', 'hebben', 'to study'],
  ['sturen', 'stuur', 'hebben', 'to send'],
  ['tanken', 'tank', 'hebben', 'to refuel'],
  ['tekenen', 'teken', 'hebben', 'to draw, to sign'],
  ['telefoneren', 'telefoneer', 'hebben', 'to telephone'],
  ['tellen', 'tel', 'hebben', 'to count'],
  ['testen', 'test', 'hebben', 'to test'],
  ['tikken', 'tik', 'hebben', 'to tap'],
  ['tolereren', 'tolereer', 'hebben', 'to tolerate'],
  ['tonen', 'toon', 'hebben', 'to show'],
  ['trainen', 'train', 'hebben', 'to train'],
  ['trappen', 'trap', 'hebben', 'to kick, to pedal'],
  ['treuren', 'treur', 'hebben', 'to mourn'],
  ['trillen', 'tril', 'hebben', 'to tremble'],
  ['troosten', 'troost', 'hebben', 'to comfort'],
  ['trouwen', 'trouw', 'zijn', 'to marry'],
  ['twijfelen', 'twijfel', 'hebben', 'to doubt'],
  ['typen', 'typ', 'hebben', 'to type'],
  ['vegen', 'veeg', 'hebben', 'to sweep'],
  ['veranderen', 'verander', 'hebben|zijn', 'to change'],
  ['verbazen', 'verbaas', 'hebben', 'to amaze'],
  ['verdedigen', 'verdedig', 'hebben', 'to defend'],
  ['verdienen', 'verdien', 'hebben', 'to earn, to deserve'],
  ['verdwalen', 'verdwaal', 'zijn', 'to get lost'],
  ['vergissen', 'vergis', 'hebben', 'to be mistaken'],
  ['verhuizen', 'verhuis', 'zijn', 'to move house'],
  ['verklaren', 'verklaar', 'hebben', 'to explain, to declare'],
  ['verlangen', 'verlang', 'hebben', 'to long for'],
  ['vermoeden', 'vermoed', 'hebben', 'to suspect'],
  ['vernietigen', 'vernietig', 'hebben', 'to destroy'],
  ['veroorzaken', 'veroorzaak', 'hebben', 'to cause'],
  ['verpakken', 'verpak', 'hebben', 'to package'],
  ['verrassen', 'verras', 'hebben', 'to surprise'],
  ['versieren', 'versier', 'hebben', 'to decorate'],
  ['verspreiden', 'verspreid', 'hebben', 'to spread'],
  ['vertalen', 'vertaal', 'hebben', 'to translate'],
  ['vertellen', 'vertel', 'hebben', 'to tell'],
  ['vertrouwen', 'vertrouw', 'hebben', 'to trust'],
  ['verven', 'verf', 'hebben', 'to paint (a wall)'],
  ['verwachten', 'verwacht', 'hebben', 'to expect'],
  ['verzamelen', 'verzamel', 'hebben', 'to collect'],
  ['verzorgen', 'verzorg', 'hebben', 'to take care of'],
  ['vieren', 'vier', 'hebben', 'to celebrate'],
  ['vissen', 'vis', 'hebben', 'to fish'],
  ['vloeken', 'vloek', 'hebben', 'to curse'],
  ['voelen', 'voel', 'hebben', 'to feel'],
  ['voetballen', 'voetbal', 'hebben', 'to play football'],
  ['volgen', 'volg', 'hebben', 'to follow'],
  ['voorspellen', 'voorspel', 'hebben', 'to predict'],
  ['vormen', 'vorm', 'hebben', 'to form'],
  ['vrezen', 'vrees', 'hebben', 'to fear'],
  ['vullen', 'vul', 'hebben', 'to fill'],
  ['waarderen', 'waardeer', 'hebben', 'to appreciate'],
  ['wachten', 'wacht', 'hebben', 'to wait'],
  ['wagen', 'waag', 'hebben', 'to dare, to risk'],
  ['wandelen', 'wandel', 'hebben|zijn', 'to stroll'],
  ['weigeren', 'weiger', 'hebben', 'to refuse'],
  ['wekken', 'wek', 'hebben', 'to wake'],
  ['wennen', 'wen', 'hebben|zijn', 'to get used to'],
  ['wensen', 'wens', 'hebben', 'to wish'],
  ['werken', 'werk', 'hebben', 'to work'],
  ['wijzigen', 'wijzig', 'hebben', 'to modify'],
  ['winkelen', 'winkel', 'hebben', 'to shop'],
  ['wisselen', 'wissel', 'hebben', 'to change, to exchange'],
  ['wonen', 'woon', 'hebben', 'to live, to reside'],
  ['worstelen', 'worstel', 'hebben', 'to wrestle'],
  ['zaaien', 'zaai', 'hebben', 'to sow'],
  ['zagen', 'zaag', 'hebben', 'to saw'],
  ['zakken', 'zak', 'zijn', 'to sink, to fail'],
  ['zeilen', 'zeil', 'hebben|zijn', 'to sail'],
  ['zetten', 'zet', 'hebben', 'to put, to set'],
  ['zeuren', 'zeur', 'hebben', 'to nag'],
  ['zoenen', 'zoen', 'hebben', 'to kiss'],
  ['zorgen', 'zorg', 'hebben', 'to care, to see to'],
  ['zuchten', 'zucht', 'hebben', 'to sigh'],
  ['zwaaien', 'zwaai', 'hebben', 'to wave'],
  ['zweten', 'zweet', 'hebben', 'to sweat'],
];

/**
 * Strong / irregular verbs: [infinitive, stem, pastSg, pastPl, participle, aux, english]
 *
 * The past forms and the participle are given outright - there is no rule that
 * predicts ablaut. The present tense is still derived from `stem`, since strong
 * verbs conjugate regularly in the present (see PRESENT_OVERRIDES for the
 * handful that do not).
 */
export const STRONG = [
  // --- class 1: ij - ee - e ---
  ['bekijken', 'bekijk', 'bekeek', 'bekeken', 'bekeken', 'hebben', 'to look at'],
  ['begrijpen', 'begrijp', 'begreep', 'begrepen', 'begrepen', 'hebben', 'to understand'],
  ['beschrijven', 'beschrijf', 'beschreef', 'beschreven', 'beschreven', 'hebben', 'to describe'],
  ['bewijzen', 'bewijs', 'bewees', 'bewezen', 'bewezen', 'hebben', 'to prove'],
  ['bijten', 'bijt', 'beet', 'beten', 'gebeten', 'hebben', 'to bite'],
  ['blijken', 'blijk', 'bleek', 'bleken', 'gebleken', 'zijn', 'to turn out'],
  ['blijven', 'blijf', 'bleef', 'bleven', 'gebleven', 'zijn', 'to stay'],
  ['drijven', 'drijf', 'dreef', 'dreven', 'gedreven', 'hebben', 'to float, to drive'],
  ['glijden', 'glijd', 'gleed', 'gleden', 'gegleden', 'zijn', 'to slide'],
  ['grijpen', 'grijp', 'greep', 'grepen', 'gegrepen', 'hebben', 'to grab'],
  ['kijken', 'kijk', 'keek', 'keken', 'gekeken', 'hebben', 'to look'],
  ['knijpen', 'knijp', 'kneep', 'knepen', 'geknepen', 'hebben', 'to pinch'],
  ['krijgen', 'krijg', 'kreeg', 'kregen', 'gekregen', 'hebben', 'to get, to receive'],
  ['lijden', 'lijd', 'leed', 'leden', 'geleden', 'hebben', 'to suffer'],
  ['lijken', 'lijk', 'leek', 'leken', 'geleken', 'hebben', 'to seem'],
  ['mijden', 'mijd', 'meed', 'meden', 'gemeden', 'hebben', 'to avoid'],
  ['ontbijten', 'ontbijt', 'ontbeet', 'ontbeten', 'ontbeten', 'hebben', 'to have breakfast'],
  ['overlijden', 'overlijd', 'overleed', 'overleden', 'overleden', 'zijn', 'to pass away'],
  ['prijzen', 'prijs', 'prees', 'prezen', 'geprezen', 'hebben', 'to praise'],
  ['rijden', 'rijd', 'reed', 'reden', 'gereden', 'hebben|zijn', 'to drive, to ride'],
  ['rijzen', 'rijs', 'rees', 'rezen', 'gerezen', 'zijn', 'to rise'],
  ['schijnen', 'schijn', 'scheen', 'schenen', 'geschenen', 'hebben', 'to shine, to seem'],
  ['schrijven', 'schrijf', 'schreef', 'schreven', 'geschreven', 'hebben', 'to write'],
  ['slijpen', 'slijp', 'sleep', 'slepen', 'geslepen', 'hebben', 'to sharpen'],
  ['snijden', 'snijd', 'sneed', 'sneden', 'gesneden', 'hebben', 'to cut'],
  ['splijten', 'splijt', 'spleet', 'spleten', 'gespleten', 'hebben', 'to split'],
  ['stijgen', 'stijg', 'steeg', 'stegen', 'gestegen', 'zijn', 'to rise, to climb'],
  ['strijden', 'strijd', 'streed', 'streden', 'gestreden', 'hebben', 'to fight'],
  ['strijken', 'strijk', 'streek', 'streken', 'gestreken', 'hebben', 'to iron'],
  ['verdwijnen', 'verdwijn', 'verdween', 'verdwenen', 'verdwenen', 'zijn', 'to disappear'],
  ['vergelijken', 'vergelijk', 'vergeleek', 'vergeleken', 'vergeleken', 'hebben', 'to compare'],
  ['verwijten', 'verwijt', 'verweet', 'verweten', 'verweten', 'hebben', 'to reproach'],
  ['wijzen', 'wijs', 'wees', 'wezen', 'gewezen', 'hebben', 'to point'],
  ['wrijven', 'wrijf', 'wreef', 'wreven', 'gewreven', 'hebben', 'to rub'],
  ['zwijgen', 'zwijg', 'zweeg', 'zwegen', 'gezwegen', 'hebben', 'to be silent'],

  // --- class 2a: ie - oo - o ---
  ['bedriegen', 'bedrieg', 'bedroog', 'bedrogen', 'bedrogen', 'hebben', 'to deceive'],
  ['bieden', 'bied', 'bood', 'boden', 'geboden', 'hebben', 'to offer'],
  ['genieten', 'geniet', 'genoot', 'genoten', 'genoten', 'hebben', 'to enjoy'],
  ['gieten', 'giet', 'goot', 'goten', 'gegoten', 'hebben', 'to pour'],
  ['kiezen', 'kies', 'koos', 'kozen', 'gekozen', 'hebben', 'to choose'],
  ['liegen', 'lieg', 'loog', 'logen', 'gelogen', 'hebben', 'to lie, to tell an untruth'],
  ['schieten', 'schiet', 'schoot', 'schoten', 'geschoten', 'hebben', 'to shoot'],
  ['verbieden', 'verbied', 'verbood', 'verboden', 'verboden', 'hebben', 'to forbid'],
  ['verliezen', 'verlies', 'verloor', 'verloren', 'verloren', 'hebben', 'to lose'],
  ['vliegen', 'vlieg', 'vloog', 'vlogen', 'gevlogen', 'hebben|zijn', 'to fly'],
  ['vriezen', 'vries', 'vroor', 'vroren', 'gevroren', 'hebben', 'to freeze'],

  // --- class 2b: ui - oo - o ---
  ['besluiten', 'besluit', 'besloot', 'besloten', 'besloten', 'hebben', 'to decide'],
  ['buigen', 'buig', 'boog', 'bogen', 'gebogen', 'hebben', 'to bend'],
  ['druipen', 'druip', 'droop', 'dropen', 'gedropen', 'hebben', 'to drip'],
  ['duiken', 'duik', 'dook', 'doken', 'gedoken', 'hebben|zijn', 'to dive'],
  ['fluiten', 'fluit', 'floot', 'floten', 'gefloten', 'hebben', 'to whistle'],
  ['kruipen', 'kruip', 'kroop', 'kropen', 'gekropen', 'hebben|zijn', 'to crawl'],
  ['ruiken', 'ruik', 'rook', 'roken', 'geroken', 'hebben', 'to smell'],
  ['schuiven', 'schuif', 'schoof', 'schoven', 'geschoven', 'hebben', 'to push, to shove'],
  ['sluipen', 'sluip', 'sloop', 'slopen', 'geslopen', 'hebben|zijn', 'to sneak'],
  ['sluiten', 'sluit', 'sloot', 'sloten', 'gesloten', 'hebben', 'to close'],
  ['snuiven', 'snuif', 'snoof', 'snoven', 'gesnoven', 'hebben', 'to sniff'],
  ['spuiten', 'spuit', 'spoot', 'spoten', 'gespoten', 'hebben', 'to spray'],
  ['stuiven', 'stuif', 'stoof', 'stoven', 'gestoven', 'hebben', 'to blow about'],
  ['zuigen', 'zuig', 'zoog', 'zogen', 'gezogen', 'hebben', 'to suck'],

  // --- class 3a: i - o - o ---
  ['beginnen', 'begin', 'begon', 'begonnen', 'begonnen', 'zijn', 'to begin'],
  ['binden', 'bind', 'bond', 'bonden', 'gebonden', 'hebben', 'to tie'],
  ['blinken', 'blink', 'blonk', 'blonken', 'geblonken', 'hebben', 'to shine'],
  ['dringen', 'dring', 'drong', 'drongen', 'gedrongen', 'hebben', 'to push, to urge'],
  ['drinken', 'drink', 'dronk', 'dronken', 'gedronken', 'hebben', 'to drink'],
  ['dwingen', 'dwing', 'dwong', 'dwongen', 'gedwongen', 'hebben', 'to force'],
  ['glimmen', 'glim', 'glom', 'glommen', 'geglommen', 'hebben', 'to glow'],
  ['klimmen', 'klim', 'klom', 'klommen', 'geklommen', 'hebben|zijn', 'to climb'],
  ['klinken', 'klink', 'klonk', 'klonken', 'geklonken', 'hebben', 'to sound'],
  ['krimpen', 'krimp', 'kromp', 'krompen', 'gekrompen', 'zijn', 'to shrink'],
  ['schrikken', 'schrik', 'schrok', 'schrokken', 'geschrokken', 'zijn', 'to be startled'],
  ['spinnen', 'spin', 'spon', 'sponnen', 'gesponnen', 'hebben', 'to spin'],
  ['springen', 'spring', 'sprong', 'sprongen', 'gesprongen', 'hebben|zijn', 'to jump'],
  ['stinken', 'stink', 'stonk', 'stonken', 'gestonken', 'hebben', 'to stink'],
  ['verbinden', 'verbind', 'verbond', 'verbonden', 'verbonden', 'hebben', 'to connect'],
  ['verzinnen', 'verzin', 'verzon', 'verzonnen', 'verzonnen', 'hebben', 'to make up'],
  ['vinden', 'vind', 'vond', 'vonden', 'gevonden', 'hebben', 'to find'],
  ['winnen', 'win', 'won', 'wonnen', 'gewonnen', 'hebben', 'to win'],
  ['wringen', 'wring', 'wrong', 'wrongen', 'gewrongen', 'hebben', 'to wring'],
  ['zingen', 'zing', 'zong', 'zongen', 'gezongen', 'hebben', 'to sing'],
  ['zinken', 'zink', 'zonk', 'zonken', 'gezonken', 'zijn', 'to sink'],

  // --- class 3b: e - o - o ---
  ['bederven', 'bederf', 'bedierf', 'bedierven', 'bedorven', 'zijn', 'to spoil'],
  ['bergen', 'berg', 'borg', 'borgen', 'geborgen', 'hebben', 'to store away'],
  ['gelden', 'geld', 'gold', 'golden', 'gegolden', 'hebben', 'to apply, to be valid'],
  ['helpen', 'help', 'hielp', 'hielpen', 'geholpen', 'hebben', 'to help'],
  ['schelden', 'scheld', 'schold', 'scholden', 'gescholden', 'hebben', 'to curse'],
  ['schenken', 'schenk', 'schonk', 'schonken', 'geschonken', 'hebben', 'to pour, to give'],
  ['smelten', 'smelt', 'smolt', 'smolten', 'gesmolten', 'zijn', 'to melt'],
  ['sterven', 'sterf', 'stierf', 'stierven', 'gestorven', 'zijn', 'to die'],
  ['treffen', 'tref', 'trof', 'troffen', 'getroffen', 'hebben', 'to hit, to strike'],
  ['trekken', 'trek', 'trok', 'trokken', 'getrokken', 'hebben', 'to pull'],
  ['vechten', 'vecht', 'vocht', 'vochten', 'gevochten', 'hebben', 'to fight'],
  ['verbergen', 'verberg', 'verborg', 'verborgen', 'verborgen', 'hebben', 'to hide'],
  ['vertrekken', 'vertrek', 'vertrok', 'vertrokken', 'vertrokken', 'zijn', 'to depart'],
  ['werpen', 'werp', 'wierp', 'wierpen', 'geworpen', 'hebben', 'to throw'],
  ['zenden', 'zend', 'zond', 'zonden', 'gezonden', 'hebben', 'to send'],
  ['zwellen', 'zwel', 'zwol', 'zwollen', 'gezwollen', 'zijn', 'to swell'],
  ['zwemmen', 'zwem', 'zwom', 'zwommen', 'gezwommen', 'hebben|zijn', 'to swim'],
  ['zwerven', 'zwerf', 'zwierf', 'zwierven', 'gezworven', 'hebben', 'to wander'],

  // --- class 4: e - a/aa - o ---
  ['bespreken', 'bespreek', 'besprak', 'bespraken', 'besproken', 'hebben', 'to discuss'],
  ['bevelen', 'beveel', 'beval', 'bevalen', 'bevolen', 'hebben', 'to command'],
  ['bewegen', 'beweeg', 'bewoog', 'bewogen', 'bewogen', 'hebben', 'to move'],
  ['breken', 'breek', 'brak', 'braken', 'gebroken', 'hebben', 'to break'],
  ['komen', 'kom', 'kwam', 'kwamen', 'gekomen', 'zijn', 'to come'],
  ['nemen', 'neem', 'nam', 'namen', 'genomen', 'hebben', 'to take'],
  ['ontbreken', 'ontbreek', 'ontbrak', 'ontbraken', 'ontbroken', 'hebben', 'to be missing'],
  ['scheren', 'scheer', 'schoor', 'schoren', 'geschoren', 'hebben', 'to shave'],
  ['spreken', 'spreek', 'sprak', 'spraken', 'gesproken', 'hebben', 'to speak'],
  ['steken', 'steek', 'stak', 'staken', 'gestoken', 'hebben', 'to sting, to stab'],
  ['stelen', 'steel', 'stal', 'stalen', 'gestolen', 'hebben', 'to steal'],
  ['treden', 'treed', 'trad', 'traden', 'getreden', 'zijn', 'to step'],
  ['wegen', 'weeg', 'woog', 'wogen', 'gewogen', 'hebben', 'to weigh'],
  ['zweren', 'zweer', 'zwoer', 'zwoeren', 'gezworen', 'hebben', 'to swear'],

  // --- class 5: e - a/aa - e ---
  ['bezitten', 'bezit', 'bezat', 'bezaten', 'bezeten', 'hebben', 'to own'],
  ['bidden', 'bid', 'bad', 'baden', 'gebeden', 'hebben', 'to pray'],
  ['eten', 'eet', 'at', 'aten', 'gegeten', 'hebben', 'to eat'],
  ['genezen', 'genees', 'genas', 'genazen', 'genezen', 'zijn', 'to heal'],
  ['geven', 'geef', 'gaf', 'gaven', 'gegeven', 'hebben', 'to give'],
  ['lezen', 'lees', 'las', 'lazen', 'gelezen', 'hebben', 'to read'],
  ['liggen', 'lig', 'lag', 'lagen', 'gelegen', 'hebben', 'to lie, to be situated'],
  ['meten', 'meet', 'mat', 'maten', 'gemeten', 'hebben', 'to measure'],
  ['vergeten', 'vergeet', 'vergat', 'vergaten', 'vergeten', 'zijn|hebben', 'to forget'],
  ['vreten', 'vreet', 'vrat', 'vraten', 'gevreten', 'hebben', 'to devour'],
  ['zien', 'zie', 'zag', 'zagen', 'gezien', 'hebben', 'to see'],
  ['zitten', 'zit', 'zat', 'zaten', 'gezeten', 'hebben', 'to sit'],

  // --- class 6: a - oe - a ---
  ['dragen', 'draag', 'droeg', 'droegen', 'gedragen', 'hebben', 'to carry, to wear'],
  ['graven', 'graaf', 'groef', 'groeven', 'gegraven', 'hebben', 'to dig'],
  ['slaan', 'sla', 'sloeg', 'sloegen', 'geslagen', 'hebben', 'to hit'],
  ['varen', 'vaar', 'voer', 'voeren', 'gevaren', 'hebben|zijn', 'to sail'],

  // --- class 7: vowel - ie/i - same vowel ---
  ['bestaan', 'besta', 'bestond', 'bestonden', 'bestaan', 'hebben', 'to exist'],
  ['bevallen', 'beval', 'beviel', 'bevielen', 'bevallen', 'zijn', 'to please, to give birth'],
  ['blazen', 'blaas', 'blies', 'bliezen', 'geblazen', 'hebben', 'to blow'],
  ['gaan', 'ga', 'ging', 'gingen', 'gegaan', 'zijn', 'to go'],
  ['hangen', 'hang', 'hing', 'hingen', 'gehangen', 'hebben', 'to hang'],
  ['houden', 'houd', 'hield', 'hielden', 'gehouden', 'hebben', 'to hold, to keep'],
  ['laten', 'laat', 'liet', 'lieten', 'gelaten', 'hebben', 'to let'],
  ['lopen', 'loop', 'liep', 'liepen', 'gelopen', 'hebben|zijn', 'to walk'],
  ['ontslaan', 'ontsla', 'ontsloeg', 'ontsloegen', 'ontslagen', 'hebben', 'to dismiss'],
  ['ontstaan', 'ontsta', 'ontstond', 'ontstonden', 'ontstaan', 'zijn', 'to arise'],
  ['onthouden', 'onthoud', 'onthield', 'onthielden', 'onthouden', 'hebben', 'to remember'],
  ['roepen', 'roep', 'riep', 'riepen', 'geroepen', 'hebben', 'to call'],
  ['slapen', 'slaap', 'sliep', 'sliepen', 'geslapen', 'hebben', 'to sleep'],
  ['staan', 'sta', 'stond', 'stonden', 'gestaan', 'hebben', 'to stand'],
  ['vallen', 'val', 'viel', 'vielen', 'gevallen', 'zijn', 'to fall'],
  ['vangen', 'vang', 'ving', 'vingen', 'gevangen', 'hebben', 'to catch'],
  ['verlaten', 'verlaat', 'verliet', 'verlieten', 'verlaten', 'hebben', 'to leave'],
  ['verstaan', 'versta', 'verstond', 'verstonden', 'verstaan', 'hebben', 'to understand'],
  ['vervangen', 'vervang', 'verving', 'vervingen', 'vervangen', 'hebben', 'to replace'],

  // --- irregular: dental past with a vowel change, plus the modals ---
  ['bezoeken', 'bezoek', 'bezocht', 'bezochten', 'bezocht', 'hebben', 'to visit'],
  ['brengen', 'breng', 'bracht', 'brachten', 'gebracht', 'hebben', 'to bring'],
  ['denken', 'denk', 'dacht', 'dachten', 'gedacht', 'hebben', 'to think'],
  ['doen', 'doe', 'deed', 'deden', 'gedaan', 'hebben', 'to do'],
  ['durven', 'durf', 'durfde|dorst', 'durfden|dorsten', 'gedurfd', 'hebben', 'to dare'],
  ['hebben', 'heb', 'had', 'hadden', 'gehad', 'hebben', 'to have'],
  ['kopen', 'koop', 'kocht', 'kochten', 'gekocht', 'hebben', 'to buy'],
  ['kunnen', 'kan', 'kon', 'konden', 'gekund', 'hebben', 'to be able to, can'],
  ['moeten', 'moet', 'moest', 'moesten', 'gemoeten', 'hebben', 'to have to, must'],
  ['mogen', 'mag', 'mocht', 'mochten', 'gemogen', 'hebben', 'to be allowed to, may'],
  ['verkopen', 'verkoop', 'verkocht', 'verkochten', 'verkocht', 'hebben', 'to sell'],
  ['verzoeken', 'verzoek', 'verzocht', 'verzochten', 'verzocht', 'hebben', 'to request'],
  ['weten', 'weet', 'wist', 'wisten', 'geweten', 'hebben', 'to know a fact'],
  ['willen', 'wil', 'wilde|wou', 'wilden|wouden', 'gewild', 'hebben', 'to want'],
  ['worden', 'word', 'werd', 'werden', 'geworden', 'zijn', 'to become'],
  ['zeggen', 'zeg', 'zei', 'zeiden', 'gezegd', 'hebben', 'to say'],
  ['zijn', 'ben', 'was', 'waren', 'geweest', 'zijn', 'to be'],
  ['zoeken', 'zoek', 'zocht', 'zochten', 'gezocht', 'hebben', 'to look for'],
];

/**
 * Mixed verbs: a weak past with a strong participle, or the reverse.
 * Same tuple shape as STRONG. These are the ones learners get wrong most,
 * because neither half predicts the other (vragen -> vroeg but gevraagd).
 */
export const MIXED = [
  ['bakken', 'bak', 'bakte', 'bakten', 'gebakken', 'hebben', 'to bake'],
  ['braden', 'braad', 'braadde', 'braadden', 'gebraden', 'hebben', 'to roast'],
  ['ervaren', 'ervaar', 'ervoer', 'ervoeren', 'ervaren', 'hebben', 'to experience'],
  ['heten', 'heet', 'heette', 'heetten', 'geheten', 'hebben', 'to be called'],
  ['jagen', 'jaag', 'jaagde|joeg', 'jaagden|joegen', 'gejaagd', 'hebben', 'to hunt'],
  ['lachen', 'lach', 'lachte', 'lachten', 'gelachen', 'hebben', 'to laugh'],
  ['laden', 'laad', 'laadde', 'laadden', 'geladen', 'hebben', 'to load'],
  ['malen', 'maal', 'maalde', 'maalden', 'gemalen', 'hebben', 'to grind'],
  ['raden', 'raad', 'raadde', 'raadden', 'geraden', 'hebben', 'to guess'],
  ['scheiden', 'scheid', 'scheidde', 'scheidden', 'gescheiden', 'hebben|zijn', 'to separate'],
  ['spannen', 'span', 'spande', 'spanden', 'gespannen', 'hebben', 'to tighten'],
  ['vouwen', 'vouw', 'vouwde', 'vouwden', 'gevouwen', 'hebben', 'to fold'],
  ['vragen', 'vraag', 'vroeg', 'vroegen', 'gevraagd', 'hebben', 'to ask'],
  ['waaien', 'waai', 'waaide|woei', 'waaiden|woeien', 'gewaaid', 'hebben', 'to blow, of wind'],
  ['wassen', 'was', 'waste', 'wasten', 'gewassen', 'hebben', 'to wash'],
  ['weven', 'weef', 'weefde', 'weefden', 'geweven', 'hebben', 'to weave'],
];

/**
 * The six verbs whose present tense is not stem + regular endings.
 * `zullen` is present/past only - it has no past participle in modern Dutch.
 */
export const PRESENT_OVERRIDES = {
  zijn: { ik: 'ben', jij: 'bent', hijzij: 'is', wij: 'zijn' },
  hebben: { ik: 'heb', jij: 'hebt', hijzij: 'heeft', wij: 'hebben' },
  kunnen: { ik: 'kan', jij: 'kunt|kan', hijzij: 'kan', wij: 'kunnen' },
  mogen: { ik: 'mag', jij: 'mag', hijzij: 'mag', wij: 'mogen' },
  willen: { ik: 'wil', jij: 'wilt|wil', hijzij: 'wil', wij: 'willen' },
  zullen: { ik: 'zal', jij: 'zult|zal', hijzij: 'zal', wij: 'zullen' },
};

/**
 * zullen is handled on its own: modal, no participle, so the perfect column
 * repeats the double-infinitive construction that Dutch actually uses.
 */
export const ZULLEN = {
  infinitive: 'zullen',
  english: 'shall, will',
  past: { ik: 'zou', jij: 'zou', hijzij: 'zou', wij: 'zouden' },
  note: 'Modal: no past participle. The VTT column shows the infinitive construction.',
  perfect: {
    ik: 'heb zullen', jij: 'hebt zullen', hijzij: 'heeft zullen', wij: 'hebben zullen',
  },
};

/**
 * Words where an apparent unstressed prefix is part of the root, so the
 * participle still takes ge-: bellen -> gebeld, not "beld".
 */
export const FALSE_PREFIXES = ['bellen', 'verven'];

/** Inseparable prefixes the ge?-detector does not catch on its own. */
export const EXTRA_NO_GE = ['overtuigen', 'voorspellen'];
